name = "Deadlocks End"
author = "FrigidAmbiance"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2931e5180be30abbd29cc48bcbc266524ccafe2134b394d8633daa1cf1c74adb"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
