name = "Deadlocks End"
author = "FrigidAmbiance"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7671aedf13df31db77270b6b8f133be340fdb9f7fab584bd100dff50efae067f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
