name = "Deadlocks End"
author = "FrigidAmbiance"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f6dcb3d8e7977cfe278a2d961792c092538c1b37b2d8a8c16ca5c545dacec1f"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
