#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 08 13:23:32 EDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=Insanity-Shader-Universal-v1.650.zip
enableShaders=true
